language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t lukeyaegel/docker-react-f Dockerfile.dev .

script:
  - docker run -e CI=true lukeyaegel/docker-react npm test 